name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature you'd like to see
      placeholder: Add support for Redis as a caching layer...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component does this feature relate to?
      options:
        - Docker/Containers
        - PHP Implementation
        - Python Implementation
        - Node.js Implementation
        - CLI Commands
        - Database Support
        - Build System
        - Networking
        - Documentation
        - Multiple Components
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Currently, there's no way to...
        This makes it difficult to...
        Users often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Add a new command: dapp-bk cache:setup
        This would create a Redis container and configure...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: |
        1. Manually configure Redis container
        2. Use docker-compose instead
        3. ...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: |
        - Add new Dockerfile-data-redis in docker/data-nonrel/
        - Add CACHE_TYPE option to .env
        - Update build command to support cache containers
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor convenience
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - Yes, I can submit a PR
        - Yes, with guidance
        - No, but I can test it
        - No
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Links to similar features in other projects, documentation, or examples
      placeholder: |
        - https://example.com/similar-feature
        - Reference implementation: ...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, mockups, or details
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and PRs to ensure this hasn't been requested
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
        - label: I have provided clear use cases and benefits
          required: true
