name: 🔧 Maintenance/Refactoring
description: Propose code refactoring, dependency updates, or maintenance tasks
title: "[Maintenance]: "
labels: ["maintenance", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest improvements to code quality, dependencies, CI/CD, or other maintenance tasks.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What maintenance task or refactoring do you propose?
      placeholder: Update PHP dependencies to latest versions...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Maintenance Type
      description: What type of maintenance is this?
      options:
        - Dependency Update
        - Code Refactoring
        - Performance Improvement
        - CI/CD Improvement
        - Test Coverage
        - Documentation Cleanup
        - Code Style/Linting
        - Security Update
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component needs maintenance?
      options:
        - PHP Implementation
        - Python Implementation
        - Node.js Implementation
        - Docker Files
        - Build Scripts
        - Tests
        - Documentation
        - CI/CD
        - Multiple Components
        - All
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this maintenance needed?
      placeholder: |
        - Current version has security vulnerabilities
        - Code is difficult to maintain
        - Tests are flaky
        - Performance can be improved by...
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope of Changes
      description: What will be changed?
      placeholder: |
        - Update symfony/console from 5.4 to 6.0
        - Refactor BuildCommand class
        - Add unit tests for...
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Changes
      description: Will this introduce breaking changes?
      options:
        - "No - Fully backward compatible"
        - "Maybe - Need to investigate"
        - "Yes - Breaking changes expected"
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: How will this be tested?
      placeholder: |
        - Run existing test suite
        - Add new tests for...
        - Manual testing on...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this maintenance?
      options:
        - Critical - Security or breaking issue
        - High - Should be done soon
        - Medium - Normal priority
        - Low - Can wait
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked that similar maintenance isn't already planned or in progress
          required: true
        - label: This maintenance aligns with the project's goals
          required: true
